<?php
ob_start();
include ("includes/seguridad.php");
session_start(); 
include ("datosconfig.php");
$conn = new mysqli($servername, $username, $password, $dbname);
if ($conn->connect_error) {
die("Connection failed: " . $conn->connect_error);
}
$titulo = $_POST['titulo'];
$slogan = $_POST["slogan"];
$resumen = $_POST["resumen"];
$horario = $_POST["horario"];
$direccion = $_POST["direccion"];
$telefono = $_POST["telefono"];
$telefono2 = $_POST["telefono2"];
$telefono3 = $_POST["telefono3"];
$telefono_citas = $_POST["telefono_citas"];
$email = $_POST["email"];
$email_juridico = $_POST["email_juridico"];
$email_solicitudes = $_POST["email_solicitudes"];
$nit = $_POST["nit"];
$logo = $_POST["logo"];
$color_header = $_POST["color_header"];
$icono = $_POST["icono"];
$imagen = $_POST["imagen"];
$footer1 = $_POST["footer1"];
$footer2 = $_POST["footer2"];
$sustituye = array("\r\n", "\n\r", "\n", "\r");
$footer1 = str_replace($sustituye, "", $footer1);
$footer2 = str_replace($sustituye, "", $footer2);
$sSQL="Update contacto Set titulo='".$titulo."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set slogan='".$slogan."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set resumen='".$resumen."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set footer1='".$footer1."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set footer2='".$footer2."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set direccion='".$direccion."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set horario='".$horario."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set telefono='".$telefono."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set telefono2='".$telefono2."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set telefono3='".$telefono3."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set telefono_citas='".$telefono_citas."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set email='".$email."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set email_solicitudes='".$email_solicitudes."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set email_juridico='".$email_juridico."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set nit='".$nit."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set logo='".$logo."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set color_header='".$color_header."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set icono='".$icono."' Where id='1'";
$result = $conn->query($sSQL);
$sSQL="Update contacto Set imagen='".$imagen."' Where id='1'";
$result = $conn->query($sSQL);
$resultado = "exito";
header ("Location: aplicacion.php?resultado=$resultado");
ob_end_flush();
?>