<?
ob_start();
include ("includes/seguridad.php");
session_start(); 
include ("datosconfig.php");
$conn = new mysqli($servername, $username, $password, $dbname);
if ($conn->connect_error) {
die("Connection failed: " . $conn->connect_error);
}
$var = $_POST['codigo'];
$nombre = $_POST['nombre'];
$slug = strtolower($nombre);
$slug = str_replace(" ", "-", $slug);
$slug = str_replace("á", "a", $slug);
$slug = str_replace("é", "e", $slug);
$slug = str_replace("í", "i", $slug);
$slug = str_replace("ó", "o", $slug);
$slug = str_replace("ú", "u", $slug);
$slug = str_replace("Á", "a", $slug);
$slug = str_replace("É", "e", $slug);
$slug = str_replace("Í", "i", $slug);
$slug = str_replace("Ó", "o", $slug);
$slug = str_replace("Ú", "u", $slug);
$slug = str_replace("Ñ", "n", $slug);
$slug = str_replace("ñ", "n", $slug);
$slug = str_replace(":", "-", $slug);
$slug = str_replace("?", "-", $slug);
$slug = str_replace("¡", "-", $slug);
$slug = str_replace("¿", "-", $slug);
$slug = str_replace("!", "-", $slug);
$slug = str_replace("–", "-", $slug);
$slug = str_replace("'", "-", $slug);
$slug = str_replace("`", "-", $slug);
$slug = str_replace("´", "-", $slug);
$slug = str_replace("’", "-", $slug);
$slug = str_replace("_", "-", $slug);
$slug = str_replace("&", "y", $slug);
$valor = $_POST['valor'];
$imagen = $_POST['imagen'];
$resumen = $_POST["resumen"];
$sustituye = array("\r\n", "\n\r", "\n", "\r");
$resumen = str_replace($sustituye, "", $resumen);
$descripcion = $_POST["descripcion"];
$descripcion = str_replace($sustituye, "", $descripcion);
$fecha_mod = date('Y-m-d');
$sSQL="Update datoscitas Set nombre='".$nombre."' Where id = '1'";
$result = $conn->query($sSQL);
$sSQL="Update datoscitas Set slug='".$slug."' Where id = '1'";
$result = $conn->query($sSQL);
$sSQL="Update datoscitas Set resumen='".$resumen."' Where id = '1'";
$result = $conn->query($sSQL);
$sSQL="Update datoscitas Set descripcion='".$descripcion."' Where id = '1'";
$result = $conn->query($sSQL);
$sSQL="Update datoscitas Set valor='".$valor."' Where id = '1'";
$result = $conn->query($sSQL);
$sSQL="Update datoscitas Set imagen='".$imagen."' Where id = '1'";
$result = $conn->query($sSQL);
$sSQL="Update datoscitas Set mod_por='".$_SESSION['s_nombre']."' Where id = '1'";
$result = $conn->query($sSQL);
$sSQL="Update datoscitas Set fecha_mod='".$fecha_mod."' Where id = '1'";
$result = $conn->query($sSQL);
$resultado = "exito";
header ("Location: campana_club.php?codigo=$var&resultado=$resultado");
ob_end_flush();
?>